version: '3'
services:
  magic:
    image: mage_spark:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile      
    ports:
      - 6789:6789
    volumes:
      - .:/home/src
      - ${PATH_TO_GOOGLE_CREDENTIALS}:/home/src/keys/
    restart: on-failure:5